### ISSUE TITLE
User id

### ISSUE THREAD

**Issue by coolcodemy** [Muhaimin/movie-app#2]
https://github.com/Muhaimin/movie-app/blob/9bf7c56c7eec6fa6fb50873084731ab788546ae9/tests/Feature/CreateNewMovieTest.php#L24

Not sure why need to put user id in here since db will auto increment.

**Comment by Muhaimin** [comment]
I overide the creation of user id = 1, because of the watchlist function only for user id = 1, multi user not supported at this time. Also when I do the test, when the DB refresh it will auto-increment id based on previous created user, it will be error if no the the id start to auto increment from other number except for 1.

**Comment by coolcodemy** [comment]
> it will auto-increment id based on previous created user

should use `RefreshDatabase` trait in the test. So that after each test, it will reset and re-migrate
